### PR TITLE
chore: allow else & switch case indentation

### PR DESCRIPTION
**Pull request by linaGirl**
- allow an else block after if blocks containing a return statement: https://eslint.org/docs/rules/no-else-return
- enforce indentation level for case clauses in switch statements: https://eslint.org/docs/rules/indent

### CODE REVIEW

**Review by lkappeler — APPROVED** [review]

**Comment by lkappeler** [comment]
@eventEmitter Can you increase the minor version and publish the package, so the changes are pulled to the projects. This would also make the last two fixes available you made recently.

**Review by rcky — CHANGES_REQUESTED** [review]
Sorry, this is concerning your previous PR:

Just [saw](https://github.com/joinbox/eslint-config-joinbox/pull/4/commits/d8d5103896a1fb89e63eb3b8ec67e7101d69f079) that our rules contain the following lines:
```
        // allow for of loops
        'no-restricted-syntax': ['error', 'ForInStatement'],
```

Shouldn't this be:
```
         // allow for of loops
        'no-restricted-syntax': ['error', 'ForOfStatement'],
```
The [corresponding docs](https://eslint.org/docs/rules/no-restricted-syntax) state that you can specify AST nodes of the eslint parser, which - in this case - is `ForOfStatement`.

bildschirmfoto 2018-09-19 um 08 29 17

**Comment by linaGirl** [comment]
@rcky this rules says: «Rather than creating separate rules for every language feature you want to turn off, this rule allows you to configure the syntax elements you want to ***restrict*** use of. »

The rule is: 
```javascript
'no-restricted-syntax': ['error', {
            selector: 'ForInStatement',
            message: 'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.',
        }, {
            selector: 'LabeledStatement',
            message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.',
        }, {
            selector: 'WithStatement',
            message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.',
        }],
```

As i see it everything should be as it is configured now.

**Comment by rcky** [comment]
@eventEmitter sorry my bad!

**Review by rcky — APPROVED** [review]

**Pull request merged**
